run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gocritic
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
    - copyloopvar
    - exhaustive
    - prealloc
    - unconvert
    - unparam
    - misspell
    - revive
    - errorlint

linters-settings:
  gosec:
    severity: high
    confidence: medium
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - opinionated
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
