FROM golang:1.26-alpine AS builder

WORKDIR /app
RUN apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/air-verse/air@v1.61.7
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /palauth ./cmd/server

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /palauth /palauth
COPY --from=builder /app/migrations /migrations
EXPOSE 3000
ENTRYPOINT ["/palauth"]
