// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAdmins = `-- name: CountAdmins :one
SELECT count(*) FROM admin_users
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (id, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, role, created_at, has_mfa
`

type CreateAdminUserParams struct {
	ID           string `json:"id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.HasMfa,
	)
	return i, err
}

const deleteAdmin = `-- name: DeleteAdmin :exec
DELETE FROM admin_users WHERE id = $1
`

func (q *Queries) DeleteAdmin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAdmin, id)
	return err
}

const getAdminByEmail = `-- name: GetAdminByEmail :one
SELECT id, email, password_hash, role, created_at, has_mfa FROM admin_users WHERE email = $1
`

func (q *Queries) GetAdminByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.HasMfa,
	)
	return i, err
}

const getAdminByID = `-- name: GetAdminByID :one
SELECT id, email, password_hash, role, created_at, has_mfa FROM admin_users WHERE id = $1
`

func (q *Queries) GetAdminByID(ctx context.Context, id string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.HasMfa,
	)
	return i, err
}

const listAdmins = `-- name: ListAdmins :many
SELECT id, email, role, created_at FROM admin_users ORDER BY created_at DESC
`

type ListAdminsRow struct {
	ID        string             `json:"id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAdmins(ctx context.Context) ([]ListAdminsRow, error) {
	rows, err := q.db.Query(ctx, listAdmins)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAdminsRow{}
	for rows.Next() {
		var i ListAdminsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdminHasMFA = `-- name: UpdateAdminHasMFA :exec
UPDATE admin_users SET has_mfa = $2 WHERE id = $1
`

type UpdateAdminHasMFAParams struct {
	ID     string `json:"id"`
	HasMfa bool   `json:"has_mfa"`
}

func (q *Queries) UpdateAdminHasMFA(ctx context.Context, arg UpdateAdminHasMFAParams) error {
	_, err := q.db.Exec(ctx, updateAdminHasMFA, arg.ID, arg.HasMfa)
	return err
}
