// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, project_id, key_hash, key_prefix, key_type, name)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, key_hash, key_prefix, key_type, name, last_used, created_at, revoked_at
`

type CreateAPIKeyParams struct {
	ID        string  `json:"id"`
	ProjectID string  `json:"project_id"`
	KeyHash   []byte  `json:"key_hash"`
	KeyPrefix string  `json:"key_prefix"`
	KeyType   string  `json:"key_type"`
	Name      *string `json:"name"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.ProjectID,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.KeyType,
		arg.Name,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.KeyType,
		&i.Name,
		&i.LastUsed,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, project_id, key_hash, key_prefix, key_type, name, last_used, created_at, revoked_at FROM api_keys WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.KeyType,
		&i.Name,
		&i.LastUsed,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByHashWithGrace = `-- name: GetAPIKeyByHashWithGrace :one
SELECT id, project_id, key_hash, key_prefix, key_type, name, last_used, created_at, revoked_at FROM api_keys WHERE key_hash = $1 AND (revoked_at IS NULL OR revoked_at > now())
`

func (q *Queries) GetAPIKeyByHashWithGrace(ctx context.Context, keyHash []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHashWithGrace, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.KeyType,
		&i.Name,
		&i.LastUsed,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, project_id, key_hash, key_prefix, key_type, name, last_used, created_at, revoked_at FROM api_keys WHERE project_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, projectID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.KeyType,
			&i.Name,
			&i.LastUsed,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const revokeAPIKeyWithGrace = `-- name: RevokeAPIKeyWithGrace :exec
UPDATE api_keys SET revoked_at = now() + interval '30 seconds' WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIKeyWithGrace(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeAPIKeyWithGrace, id)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used = now() WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
