// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package sqlc

import (
	"context"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (id, project_id, trace_id, event_type, actor_encrypted, target_type, target_id, result, auth_method, risk_score, metadata_encrypted, prev_hash, event_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, project_id, trace_id, event_type, actor_encrypted, target_type, target_id, result, auth_method, risk_score, metadata_encrypted, prev_hash, event_hash, created_at
`

type CreateAuditLogParams struct {
	ID                string   `json:"id"`
	ProjectID         string   `json:"project_id"`
	TraceID           *string  `json:"trace_id"`
	EventType         string   `json:"event_type"`
	ActorEncrypted    []byte   `json:"actor_encrypted"`
	TargetType        *string  `json:"target_type"`
	TargetID          *string  `json:"target_id"`
	Result            string   `json:"result"`
	AuthMethod        *string  `json:"auth_method"`
	RiskScore         *float32 `json:"risk_score"`
	MetadataEncrypted []byte   `json:"metadata_encrypted"`
	PrevHash          *string  `json:"prev_hash"`
	EventHash         string   `json:"event_hash"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.ProjectID,
		arg.TraceID,
		arg.EventType,
		arg.ActorEncrypted,
		arg.TargetType,
		arg.TargetID,
		arg.Result,
		arg.AuthMethod,
		arg.RiskScore,
		arg.MetadataEncrypted,
		arg.PrevHash,
		arg.EventHash,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TraceID,
		&i.EventType,
		&i.ActorEncrypted,
		&i.TargetType,
		&i.TargetID,
		&i.Result,
		&i.AuthMethod,
		&i.RiskScore,
		&i.MetadataEncrypted,
		&i.PrevHash,
		&i.EventHash,
		&i.CreatedAt,
	)
	return i, err
}

const getLastAuditLog = `-- name: GetLastAuditLog :one
SELECT id, project_id, trace_id, event_type, actor_encrypted, target_type, target_id, result, auth_method, risk_score, metadata_encrypted, prev_hash, event_hash, created_at FROM audit_logs WHERE project_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLastAuditLog(ctx context.Context, projectID string) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getLastAuditLog, projectID)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TraceID,
		&i.EventType,
		&i.ActorEncrypted,
		&i.TargetType,
		&i.TargetID,
		&i.Result,
		&i.AuthMethod,
		&i.RiskScore,
		&i.MetadataEncrypted,
		&i.PrevHash,
		&i.EventHash,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, project_id, trace_id, event_type, actor_encrypted, target_type, target_id, result, auth_method, risk_score, metadata_encrypted, prev_hash, event_hash, created_at FROM audit_logs WHERE project_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListAuditLogsParams struct {
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TraceID,
			&i.EventType,
			&i.ActorEncrypted,
			&i.TargetType,
			&i.TargetID,
			&i.Result,
			&i.AuthMethod,
			&i.RiskScore,
			&i.MetadataEncrypted,
			&i.PrevHash,
			&i.EventHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByType = `-- name: ListAuditLogsByType :many
SELECT id, project_id, trace_id, event_type, actor_encrypted, target_type, target_id, result, auth_method, risk_score, metadata_encrypted, prev_hash, event_hash, created_at FROM audit_logs WHERE project_id = $1 AND event_type = $2 ORDER BY created_at DESC LIMIT $3 OFFSET $4
`

type ListAuditLogsByTypeParams struct {
	ProjectID string `json:"project_id"`
	EventType string `json:"event_type"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListAuditLogsByType(ctx context.Context, arg ListAuditLogsByTypeParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByType,
		arg.ProjectID,
		arg.EventType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TraceID,
			&i.EventType,
			&i.ActorEncrypted,
			&i.TargetType,
			&i.TargetID,
			&i.Result,
			&i.AuthMethod,
			&i.RiskScore,
			&i.MetadataEncrypted,
			&i.PrevHash,
			&i.EventHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
