// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs WHERE project_id = $1
`

func (q *Queries) CountAuditLogs(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogsByType = `-- name: CountAuditLogsByType :one
SELECT count(*) FROM audit_logs WHERE project_id = $1 AND event_type = $2
`

type CountAuditLogsByTypeParams struct {
	ProjectID string `json:"project_id"`
	EventType string `json:"event_type"`
}

func (q *Queries) CountAuditLogsByType(ctx context.Context, arg CountAuditLogsByTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogsByType, arg.ProjectID, arg.EventType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (id, project_id, trace_id, event_type, actor_encrypted, target_type, target_id, result, auth_method, risk_score, metadata_encrypted, prev_hash, event_hash)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, project_id, trace_id, event_type, actor_encrypted, target_type, target_id, result, auth_method, risk_score, metadata_encrypted, prev_hash, event_hash, created_at
`

type CreateAuditLogParams struct {
	ID                string   `json:"id"`
	ProjectID         string   `json:"project_id"`
	TraceID           *string  `json:"trace_id"`
	EventType         string   `json:"event_type"`
	ActorEncrypted    []byte   `json:"actor_encrypted"`
	TargetType        *string  `json:"target_type"`
	TargetID          *string  `json:"target_id"`
	Result            string   `json:"result"`
	AuthMethod        *string  `json:"auth_method"`
	RiskScore         *float32 `json:"risk_score"`
	MetadataEncrypted []byte   `json:"metadata_encrypted"`
	PrevHash          *string  `json:"prev_hash"`
	EventHash         string   `json:"event_hash"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.ID,
		arg.ProjectID,
		arg.TraceID,
		arg.EventType,
		arg.ActorEncrypted,
		arg.TargetType,
		arg.TargetID,
		arg.Result,
		arg.AuthMethod,
		arg.RiskScore,
		arg.MetadataEncrypted,
		arg.PrevHash,
		arg.EventHash,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TraceID,
		&i.EventType,
		&i.ActorEncrypted,
		&i.TargetType,
		&i.TargetID,
		&i.Result,
		&i.AuthMethod,
		&i.RiskScore,
		&i.MetadataEncrypted,
		&i.PrevHash,
		&i.EventHash,
		&i.CreatedAt,
	)
	return i, err
}

const getLastAuditLog = `-- name: GetLastAuditLog :one
SELECT id, project_id, trace_id, event_type, actor_encrypted, target_type, target_id, result, auth_method, risk_score, metadata_encrypted, prev_hash, event_hash, created_at FROM audit_logs WHERE project_id = $1 ORDER BY created_at DESC, id DESC LIMIT 1
`

func (q *Queries) GetLastAuditLog(ctx context.Context, projectID string) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getLastAuditLog, projectID)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.TraceID,
		&i.EventType,
		&i.ActorEncrypted,
		&i.TargetType,
		&i.TargetID,
		&i.Result,
		&i.AuthMethod,
		&i.RiskScore,
		&i.MetadataEncrypted,
		&i.PrevHash,
		&i.EventHash,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLogsAsc = `-- name: ListAuditLogsAsc :many
SELECT id, project_id, trace_id, event_type, actor_encrypted, target_type, target_id, result, auth_method, risk_score, metadata_encrypted, prev_hash, event_hash, created_at FROM audit_logs WHERE project_id = $1 ORDER BY created_at ASC, id ASC
`

// NOTE: No LIMIT — used by Verify() and Export() which need full chain.
// Acceptable for Phase 0 (bounded project sizes). Add streaming/batching for production scale.
func (q *Queries) ListAuditLogsAsc(ctx context.Context, projectID string) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsAsc, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TraceID,
			&i.EventType,
			&i.ActorEncrypted,
			&i.TargetType,
			&i.TargetID,
			&i.Result,
			&i.AuthMethod,
			&i.RiskScore,
			&i.MetadataEncrypted,
			&i.PrevHash,
			&i.EventHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsCursor = `-- name: ListAuditLogsCursor :many
SELECT id, project_id, trace_id, event_type, actor_encrypted, target_type, target_id, result, auth_method, risk_score, metadata_encrypted, prev_hash, event_hash, created_at FROM audit_logs
WHERE project_id = $1
  AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListAuditLogsCursorParams struct {
	ProjectID       string             `json:"project_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        string             `json:"cursor_id"`
	Lim             int32              `json:"lim"`
}

func (q *Queries) ListAuditLogsCursor(ctx context.Context, arg ListAuditLogsCursorParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsCursor,
		arg.ProjectID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TraceID,
			&i.EventType,
			&i.ActorEncrypted,
			&i.TargetType,
			&i.TargetID,
			&i.Result,
			&i.AuthMethod,
			&i.RiskScore,
			&i.MetadataEncrypted,
			&i.PrevHash,
			&i.EventHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsCursorByType = `-- name: ListAuditLogsCursorByType :many
SELECT id, project_id, trace_id, event_type, actor_encrypted, target_type, target_id, result, auth_method, risk_score, metadata_encrypted, prev_hash, event_hash, created_at FROM audit_logs
WHERE project_id = $1 AND event_type = $2
  AND (created_at < $3 OR (created_at = $3 AND id < $4))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListAuditLogsCursorByTypeParams struct {
	ProjectID       string             `json:"project_id"`
	EventType       string             `json:"event_type"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        string             `json:"cursor_id"`
	Lim             int32              `json:"lim"`
}

func (q *Queries) ListAuditLogsCursorByType(ctx context.Context, arg ListAuditLogsCursorByTypeParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsCursorByType,
		arg.ProjectID,
		arg.EventType,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TraceID,
			&i.EventType,
			&i.ActorEncrypted,
			&i.TargetType,
			&i.TargetID,
			&i.Result,
			&i.AuthMethod,
			&i.RiskScore,
			&i.MetadataEncrypted,
			&i.PrevHash,
			&i.EventHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsFirst = `-- name: ListAuditLogsFirst :many
SELECT id, project_id, trace_id, event_type, actor_encrypted, target_type, target_id, result, auth_method, risk_score, metadata_encrypted, prev_hash, event_hash, created_at FROM audit_logs
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListAuditLogsFirstParams struct {
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListAuditLogsFirst(ctx context.Context, arg ListAuditLogsFirstParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsFirst, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TraceID,
			&i.EventType,
			&i.ActorEncrypted,
			&i.TargetType,
			&i.TargetID,
			&i.Result,
			&i.AuthMethod,
			&i.RiskScore,
			&i.MetadataEncrypted,
			&i.PrevHash,
			&i.EventHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsFirstByType = `-- name: ListAuditLogsFirstByType :many
SELECT id, project_id, trace_id, event_type, actor_encrypted, target_type, target_id, result, auth_method, risk_score, metadata_encrypted, prev_hash, event_hash, created_at FROM audit_logs
WHERE project_id = $1 AND event_type = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListAuditLogsFirstByTypeParams struct {
	ProjectID string `json:"project_id"`
	EventType string `json:"event_type"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListAuditLogsFirstByType(ctx context.Context, arg ListAuditLogsFirstByTypeParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsFirstByType, arg.ProjectID, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.TraceID,
			&i.EventType,
			&i.ActorEncrypted,
			&i.TargetType,
			&i.TargetID,
			&i.Result,
			&i.AuthMethod,
			&i.RiskScore,
			&i.MetadataEncrypted,
			&i.PrevHash,
			&i.EventHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
