// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: encryption_keys.sql

package sqlc

import (
	"context"
)

const createEncryptionKey = `-- name: CreateEncryptionKey :one
INSERT INTO encryption_keys (id, project_id, user_id, encrypted_key, key_type)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, user_id, encrypted_key, key_type, created_at, revoked_at
`

type CreateEncryptionKeyParams struct {
	ID           string  `json:"id"`
	ProjectID    *string `json:"project_id"`
	UserID       *string `json:"user_id"`
	EncryptedKey []byte  `json:"encrypted_key"`
	KeyType      string  `json:"key_type"`
}

func (q *Queries) CreateEncryptionKey(ctx context.Context, arg CreateEncryptionKeyParams) (EncryptionKey, error) {
	row := q.db.QueryRow(ctx, createEncryptionKey,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.EncryptedKey,
		arg.KeyType,
	)
	var i EncryptionKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.EncryptedKey,
		&i.KeyType,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getProjectDEK = `-- name: GetProjectDEK :one
SELECT id, project_id, user_id, encrypted_key, key_type, created_at, revoked_at FROM encryption_keys
WHERE project_id = $1 AND key_type = 'project_dek' AND revoked_at IS NULL
`

func (q *Queries) GetProjectDEK(ctx context.Context, projectID *string) (EncryptionKey, error) {
	row := q.db.QueryRow(ctx, getProjectDEK, projectID)
	var i EncryptionKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.EncryptedKey,
		&i.KeyType,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserDEK = `-- name: GetUserDEK :one
SELECT id, project_id, user_id, encrypted_key, key_type, created_at, revoked_at FROM encryption_keys
WHERE user_id = $1 AND key_type = 'user_dek' AND revoked_at IS NULL
`

func (q *Queries) GetUserDEK(ctx context.Context, userID *string) (EncryptionKey, error) {
	row := q.db.QueryRow(ctx, getUserDEK, userID)
	var i EncryptionKey
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.EncryptedKey,
		&i.KeyType,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeUserDEK = `-- name: RevokeUserDEK :exec
UPDATE encryption_keys SET revoked_at = now()
WHERE user_id = $1 AND key_type = 'user_dek' AND revoked_at IS NULL
`

func (q *Queries) RevokeUserDEK(ctx context.Context, userID *string) error {
	_, err := q.db.Exec(ctx, revokeUserDEK, userID)
	return err
}
