// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hook_configs.sql

package sqlc

import (
	"context"
)

const createHookConfig = `-- name: CreateHookConfig :one
INSERT INTO hook_configs (id, project_id, event, url, signing_key_encrypted, timeout_ms, failure_mode, enabled)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, event, url, signing_key_encrypted, timeout_ms, failure_mode, enabled, created_at
`

type CreateHookConfigParams struct {
	ID                  string `json:"id"`
	ProjectID           string `json:"project_id"`
	Event               string `json:"event"`
	Url                 string `json:"url"`
	SigningKeyEncrypted []byte `json:"signing_key_encrypted"`
	TimeoutMs           int32  `json:"timeout_ms"`
	FailureMode         string `json:"failure_mode"`
	Enabled             bool   `json:"enabled"`
}

func (q *Queries) CreateHookConfig(ctx context.Context, arg CreateHookConfigParams) (HookConfig, error) {
	row := q.db.QueryRow(ctx, createHookConfig,
		arg.ID,
		arg.ProjectID,
		arg.Event,
		arg.Url,
		arg.SigningKeyEncrypted,
		arg.TimeoutMs,
		arg.FailureMode,
		arg.Enabled,
	)
	var i HookConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Event,
		&i.Url,
		&i.SigningKeyEncrypted,
		&i.TimeoutMs,
		&i.FailureMode,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const createHookLog = `-- name: CreateHookLog :one
INSERT INTO hook_logs (id, hook_config_id, project_id, event, request_body, response_body, response_status, latency_ms, result)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, hook_config_id, project_id, event, request_body, response_body, response_status, latency_ms, result, created_at
`

type CreateHookLogParams struct {
	ID             string `json:"id"`
	HookConfigID   string `json:"hook_config_id"`
	ProjectID      string `json:"project_id"`
	Event          string `json:"event"`
	RequestBody    []byte `json:"request_body"`
	ResponseBody   []byte `json:"response_body"`
	ResponseStatus *int32 `json:"response_status"`
	LatencyMs      int32  `json:"latency_ms"`
	Result         string `json:"result"`
}

func (q *Queries) CreateHookLog(ctx context.Context, arg CreateHookLogParams) (HookLog, error) {
	row := q.db.QueryRow(ctx, createHookLog,
		arg.ID,
		arg.HookConfigID,
		arg.ProjectID,
		arg.Event,
		arg.RequestBody,
		arg.ResponseBody,
		arg.ResponseStatus,
		arg.LatencyMs,
		arg.Result,
	)
	var i HookLog
	err := row.Scan(
		&i.ID,
		&i.HookConfigID,
		&i.ProjectID,
		&i.Event,
		&i.RequestBody,
		&i.ResponseBody,
		&i.ResponseStatus,
		&i.LatencyMs,
		&i.Result,
		&i.CreatedAt,
	)
	return i, err
}

const deleteHookConfig = `-- name: DeleteHookConfig :exec
DELETE FROM hook_configs WHERE id = $1 AND project_id = $2
`

type DeleteHookConfigParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteHookConfig(ctx context.Context, arg DeleteHookConfigParams) error {
	_, err := q.db.Exec(ctx, deleteHookConfig, arg.ID, arg.ProjectID)
	return err
}

const getHookConfig = `-- name: GetHookConfig :one
SELECT id, project_id, event, url, signing_key_encrypted, timeout_ms, failure_mode, enabled, created_at FROM hook_configs
WHERE id = $1 AND project_id = $2
`

type GetHookConfigParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetHookConfig(ctx context.Context, arg GetHookConfigParams) (HookConfig, error) {
	row := q.db.QueryRow(ctx, getHookConfig, arg.ID, arg.ProjectID)
	var i HookConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Event,
		&i.Url,
		&i.SigningKeyEncrypted,
		&i.TimeoutMs,
		&i.FailureMode,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledHooksByProjectEvent = `-- name: ListEnabledHooksByProjectEvent :many
SELECT id, project_id, event, url, signing_key_encrypted, timeout_ms, failure_mode, enabled, created_at FROM hook_configs
WHERE project_id = $1 AND event = $2 AND enabled = true
ORDER BY created_at ASC
`

type ListEnabledHooksByProjectEventParams struct {
	ProjectID string `json:"project_id"`
	Event     string `json:"event"`
}

func (q *Queries) ListEnabledHooksByProjectEvent(ctx context.Context, arg ListEnabledHooksByProjectEventParams) ([]HookConfig, error) {
	rows, err := q.db.Query(ctx, listEnabledHooksByProjectEvent, arg.ProjectID, arg.Event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HookConfig{}
	for rows.Next() {
		var i HookConfig
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Event,
			&i.Url,
			&i.SigningKeyEncrypted,
			&i.TimeoutMs,
			&i.FailureMode,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHookLogs = `-- name: ListHookLogs :many
SELECT id, hook_config_id, project_id, event, request_body, response_body, response_status, latency_ms, result, created_at FROM hook_logs
WHERE hook_config_id = $1 AND project_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListHookLogsParams struct {
	HookConfigID string `json:"hook_config_id"`
	ProjectID    string `json:"project_id"`
	Limit        int32  `json:"limit"`
}

func (q *Queries) ListHookLogs(ctx context.Context, arg ListHookLogsParams) ([]HookLog, error) {
	rows, err := q.db.Query(ctx, listHookLogs, arg.HookConfigID, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HookLog{}
	for rows.Next() {
		var i HookLog
		if err := rows.Scan(
			&i.ID,
			&i.HookConfigID,
			&i.ProjectID,
			&i.Event,
			&i.RequestBody,
			&i.ResponseBody,
			&i.ResponseStatus,
			&i.LatencyMs,
			&i.Result,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHooksByProject = `-- name: ListHooksByProject :many
SELECT id, project_id, event, url, signing_key_encrypted, timeout_ms, failure_mode, enabled, created_at FROM hook_configs
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListHooksByProject(ctx context.Context, projectID string) ([]HookConfig, error) {
	rows, err := q.db.Query(ctx, listHooksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HookConfig{}
	for rows.Next() {
		var i HookConfig
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Event,
			&i.Url,
			&i.SigningKeyEncrypted,
			&i.TimeoutMs,
			&i.FailureMode,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHookConfig = `-- name: UpdateHookConfig :one
UPDATE hook_configs
SET event = $3, url = $4, timeout_ms = $5, failure_mode = $6, enabled = $7
WHERE id = $1 AND project_id = $2
RETURNING id, project_id, event, url, signing_key_encrypted, timeout_ms, failure_mode, enabled, created_at
`

type UpdateHookConfigParams struct {
	ID          string `json:"id"`
	ProjectID   string `json:"project_id"`
	Event       string `json:"event"`
	Url         string `json:"url"`
	TimeoutMs   int32  `json:"timeout_ms"`
	FailureMode string `json:"failure_mode"`
	Enabled     bool   `json:"enabled"`
}

func (q *Queries) UpdateHookConfig(ctx context.Context, arg UpdateHookConfigParams) (HookConfig, error) {
	row := q.db.QueryRow(ctx, updateHookConfig,
		arg.ID,
		arg.ProjectID,
		arg.Event,
		arg.Url,
		arg.TimeoutMs,
		arg.FailureMode,
		arg.Enabled,
	)
	var i HookConfig
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Event,
		&i.Url,
		&i.SigningKeyEncrypted,
		&i.TimeoutMs,
		&i.FailureMode,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}
