// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identities.sql

package sqlc

import (
	"context"
)

const countIdentitiesByUser = `-- name: CountIdentitiesByUser :one
SELECT count(*) FROM identities
WHERE user_id = $1 AND project_id = $2
`

type CountIdentitiesByUserParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) CountIdentitiesByUser(ctx context.Context, arg CountIdentitiesByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIdentitiesByUser, arg.UserID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (id, project_id, user_id, provider, provider_user_id, provider_data)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, user_id, provider, provider_user_id, provider_data, created_at
`

type CreateIdentityParams struct {
	ID             string `json:"id"`
	ProjectID      string `json:"project_id"`
	UserID         string `json:"user_id"`
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
	ProviderData   []byte `json:"provider_data"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.ProviderData,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderData,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIdentity = `-- name: DeleteIdentity :exec
DELETE FROM identities
WHERE id = $1 AND user_id = $2 AND project_id = $3
`

type DeleteIdentityParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteIdentity(ctx context.Context, arg DeleteIdentityParams) error {
	_, err := q.db.Exec(ctx, deleteIdentity, arg.ID, arg.UserID, arg.ProjectID)
	return err
}

const getIdentityByProviderUser = `-- name: GetIdentityByProviderUser :one
SELECT id, project_id, user_id, provider, provider_user_id, provider_data, created_at FROM identities
WHERE project_id = $1 AND provider = $2 AND provider_user_id = $3
`

type GetIdentityByProviderUserParams struct {
	ProjectID      string `json:"project_id"`
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

func (q *Queries) GetIdentityByProviderUser(ctx context.Context, arg GetIdentityByProviderUserParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByProviderUser, arg.ProjectID, arg.Provider, arg.ProviderUserID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderData,
		&i.CreatedAt,
	)
	return i, err
}

const listIdentitiesByUser = `-- name: ListIdentitiesByUser :many
SELECT id, project_id, user_id, provider, provider_user_id, provider_data, created_at FROM identities
WHERE user_id = $1 AND project_id = $2
ORDER BY created_at DESC
`

type ListIdentitiesByUserParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) ListIdentitiesByUser(ctx context.Context, arg ListIdentitiesByUserParams) ([]Identity, error) {
	rows, err := q.db.Query(ctx, listIdentitiesByUser, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Identity{}
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.ProviderData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
