// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mfa_enrollments.sql

package sqlc

import (
	"context"
)

const createMFAEnrollment = `-- name: CreateMFAEnrollment :one
INSERT INTO mfa_enrollments (id, project_id, user_id, type, secret_encrypted, verified)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, user_id, type, secret_encrypted, verified, created_at
`

type CreateMFAEnrollmentParams struct {
	ID              string `json:"id"`
	ProjectID       string `json:"project_id"`
	UserID          string `json:"user_id"`
	Type            string `json:"type"`
	SecretEncrypted []byte `json:"secret_encrypted"`
	Verified        bool   `json:"verified"`
}

func (q *Queries) CreateMFAEnrollment(ctx context.Context, arg CreateMFAEnrollmentParams) (MfaEnrollment, error) {
	row := q.db.QueryRow(ctx, createMFAEnrollment,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Type,
		arg.SecretEncrypted,
		arg.Verified,
	)
	var i MfaEnrollment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Type,
		&i.SecretEncrypted,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMFAEnrollment = `-- name: DeleteMFAEnrollment :exec
DELETE FROM mfa_enrollments WHERE id = $1 AND project_id = $2
`

type DeleteMFAEnrollmentParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteMFAEnrollment(ctx context.Context, arg DeleteMFAEnrollmentParams) error {
	_, err := q.db.Exec(ctx, deleteMFAEnrollment, arg.ID, arg.ProjectID)
	return err
}

const deleteMFAEnrollmentsByUser = `-- name: DeleteMFAEnrollmentsByUser :exec
DELETE FROM mfa_enrollments WHERE user_id = $1 AND project_id = $2
`

type DeleteMFAEnrollmentsByUserParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteMFAEnrollmentsByUser(ctx context.Context, arg DeleteMFAEnrollmentsByUserParams) error {
	_, err := q.db.Exec(ctx, deleteMFAEnrollmentsByUser, arg.UserID, arg.ProjectID)
	return err
}

const getMFAEnrollment = `-- name: GetMFAEnrollment :one
SELECT id, project_id, user_id, type, secret_encrypted, verified, created_at FROM mfa_enrollments WHERE id = $1 AND project_id = $2
`

type GetMFAEnrollmentParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetMFAEnrollment(ctx context.Context, arg GetMFAEnrollmentParams) (MfaEnrollment, error) {
	row := q.db.QueryRow(ctx, getMFAEnrollment, arg.ID, arg.ProjectID)
	var i MfaEnrollment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Type,
		&i.SecretEncrypted,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const getMFAEnrollmentByUserAndType = `-- name: GetMFAEnrollmentByUserAndType :one
SELECT id, project_id, user_id, type, secret_encrypted, verified, created_at FROM mfa_enrollments
WHERE user_id = $1 AND project_id = $2 AND type = $3
`

type GetMFAEnrollmentByUserAndTypeParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
	Type      string `json:"type"`
}

func (q *Queries) GetMFAEnrollmentByUserAndType(ctx context.Context, arg GetMFAEnrollmentByUserAndTypeParams) (MfaEnrollment, error) {
	row := q.db.QueryRow(ctx, getMFAEnrollmentByUserAndType, arg.UserID, arg.ProjectID, arg.Type)
	var i MfaEnrollment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Type,
		&i.SecretEncrypted,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const getVerifiedMFAEnrollmentByUserAndType = `-- name: GetVerifiedMFAEnrollmentByUserAndType :one
SELECT id, project_id, user_id, type, secret_encrypted, verified, created_at FROM mfa_enrollments
WHERE user_id = $1 AND project_id = $2 AND type = $3 AND verified = true
`

type GetVerifiedMFAEnrollmentByUserAndTypeParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
	Type      string `json:"type"`
}

func (q *Queries) GetVerifiedMFAEnrollmentByUserAndType(ctx context.Context, arg GetVerifiedMFAEnrollmentByUserAndTypeParams) (MfaEnrollment, error) {
	row := q.db.QueryRow(ctx, getVerifiedMFAEnrollmentByUserAndType, arg.UserID, arg.ProjectID, arg.Type)
	var i MfaEnrollment
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Type,
		&i.SecretEncrypted,
		&i.Verified,
		&i.CreatedAt,
	)
	return i, err
}

const listMFAEnrollments = `-- name: ListMFAEnrollments :many
SELECT id, project_id, user_id, type, secret_encrypted, verified, created_at FROM mfa_enrollments
WHERE user_id = $1 AND project_id = $2
ORDER BY created_at ASC
`

type ListMFAEnrollmentsParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) ListMFAEnrollments(ctx context.Context, arg ListMFAEnrollmentsParams) ([]MfaEnrollment, error) {
	rows, err := q.db.Query(ctx, listMFAEnrollments, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MfaEnrollment{}
	for rows.Next() {
		var i MfaEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Type,
			&i.SecretEncrypted,
			&i.Verified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedMFAEnrollments = `-- name: ListVerifiedMFAEnrollments :many
SELECT id, project_id, user_id, type, secret_encrypted, verified, created_at FROM mfa_enrollments
WHERE user_id = $1 AND project_id = $2 AND verified = true
ORDER BY created_at ASC
`

type ListVerifiedMFAEnrollmentsParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) ListVerifiedMFAEnrollments(ctx context.Context, arg ListVerifiedMFAEnrollmentsParams) ([]MfaEnrollment, error) {
	rows, err := q.db.Query(ctx, listVerifiedMFAEnrollments, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MfaEnrollment{}
	for rows.Next() {
		var i MfaEnrollment
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Type,
			&i.SecretEncrypted,
			&i.Verified,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserHasMFA = `-- name: UpdateUserHasMFA :exec
UPDATE users SET has_mfa = $2, updated_at = now()
WHERE id = $1 AND project_id = $3
`

type UpdateUserHasMFAParams struct {
	ID        string `json:"id"`
	HasMfa    bool   `json:"has_mfa"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) UpdateUserHasMFA(ctx context.Context, arg UpdateUserHasMFAParams) error {
	_, err := q.db.Exec(ctx, updateUserHasMFA, arg.ID, arg.HasMfa, arg.ProjectID)
	return err
}

const verifyMFAEnrollment = `-- name: VerifyMFAEnrollment :exec
UPDATE mfa_enrollments SET verified = true
WHERE id = $1 AND project_id = $2
`

type VerifyMFAEnrollmentParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) VerifyMFAEnrollment(ctx context.Context, arg VerifyMFAEnrollmentParams) error {
	_, err := q.db.Exec(ctx, verifyMFAEnrollment, arg.ID, arg.ProjectID)
	return err
}
