// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUser struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ApiKey struct {
	ID        string             `json:"id"`
	ProjectID string             `json:"project_id"`
	KeyHash   []byte             `json:"key_hash"`
	KeyPrefix string             `json:"key_prefix"`
	KeyType   string             `json:"key_type"`
	Name      *string            `json:"name"`
	LastUsed  pgtype.Timestamptz `json:"last_used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type AuditLog struct {
	ID                string             `json:"id"`
	ProjectID         string             `json:"project_id"`
	TraceID           *string            `json:"trace_id"`
	EventType         string             `json:"event_type"`
	ActorEncrypted    []byte             `json:"actor_encrypted"`
	TargetType        *string            `json:"target_type"`
	TargetID          *string            `json:"target_id"`
	Result            string             `json:"result"`
	AuthMethod        *string            `json:"auth_method"`
	RiskScore         *float32           `json:"risk_score"`
	MetadataEncrypted []byte             `json:"metadata_encrypted"`
	PrevHash          *string            `json:"prev_hash"`
	EventHash         string             `json:"event_hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type EncryptionKey struct {
	ID           string             `json:"id"`
	ProjectID    *string            `json:"project_id"`
	UserID       *string            `json:"user_id"`
	EncryptedKey []byte             `json:"encrypted_key"`
	KeyType      string             `json:"key_type"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
}

type PasswordHistory struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Hash      string             `json:"hash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Project struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Config    []byte             `json:"config"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RefreshToken struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	UserID    string             `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	FamilyID  string             `json:"family_id"`
	ParentID  *string            `json:"parent_id"`
	Used      bool               `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	ProjectID string             `json:"project_id"`
}

type Session struct {
	ID            string             `json:"id"`
	ProjectID     string             `json:"project_id"`
	UserID        string             `json:"user_id"`
	Ip            *string            `json:"ip"`
	UserAgent     *string            `json:"user_agent"`
	DeviceFpHash  *string            `json:"device_fp_hash"`
	Acr           string             `json:"acr"`
	Amr           []byte             `json:"amr"`
	IdleTimeoutAt pgtype.Timestamptz `json:"idle_timeout_at"`
	AbsTimeoutAt  pgtype.Timestamptz `json:"abs_timeout_at"`
	LastActivity  pgtype.Timestamptz `json:"last_activity"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             string             `json:"id"`
	ProjectID      string             `json:"project_id"`
	EmailEncrypted []byte             `json:"email_encrypted"`
	EmailHash      []byte             `json:"email_hash"`
	PasswordHash   *string            `json:"password_hash"`
	EmailVerified  bool               `json:"email_verified"`
	Banned         bool               `json:"banned"`
	BanReason      *string            `json:"ban_reason"`
	Metadata       []byte             `json:"metadata"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UserConsent struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	ProjectID string             `json:"project_id"`
	Purpose   string             `json:"purpose"`
	Granted   bool               `json:"granted"`
	Version   *string            `json:"version"`
	Ip        *string            `json:"ip"`
	UserAgent *string            `json:"user_agent"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type VerificationToken struct {
	ID             string             `json:"id"`
	ProjectID      string             `json:"project_id"`
	UserID         string             `json:"user_id"`
	TokenHash      []byte             `json:"token_hash"`
	Type           string             `json:"type"`
	Used           bool               `json:"used"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	FailedAttempts int32              `json:"failed_attempts"`
}
