// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_history.sql

package sqlc

import (
	"context"
)

const createPasswordHistory = `-- name: CreatePasswordHistory :exec
INSERT INTO password_history (id, user_id, hash) VALUES ($1, $2, $3)
`

type CreatePasswordHistoryParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
	Hash   string `json:"hash"`
}

func (q *Queries) CreatePasswordHistory(ctx context.Context, arg CreatePasswordHistoryParams) error {
	_, err := q.db.Exec(ctx, createPasswordHistory, arg.ID, arg.UserID, arg.Hash)
	return err
}

const getRecentPasswords = `-- name: GetRecentPasswords :many
SELECT hash FROM password_history
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type GetRecentPasswordsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) GetRecentPasswords(ctx context.Context, arg GetRecentPasswordsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getRecentPasswords, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var hash string
		if err := rows.Scan(&hash); err != nil {
			return nil, err
		}
		items = append(items, hash)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
