// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlc

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, name, config)
VALUES ($1, $2, $3)
RETURNING id, name, config, created_at, updated_at
`

type CreateProjectParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Config []byte `json:"config"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.ID, arg.Name, arg.Config)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
DELETE FROM projects WHERE id = $1 RETURNING id
`

func (q *Queries) DeleteProject(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteProject, id)
	err := row.Scan(&id)
	return id, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, config, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, config, created_at, updated_at FROM projects ORDER BY created_at DESC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Config,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET name = $2, config = $3, updated_at = now()
WHERE id = $1
RETURNING id, name, config, created_at, updated_at
`

type UpdateProjectParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Config []byte `json:"config"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject, arg.ID, arg.Name, arg.Config)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
