// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recovery_codes.sql

package sqlc

import (
	"context"
)

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT count(*) FROM recovery_codes
WHERE user_id = $1 AND project_id = $2 AND used = false
`

type CountUnusedRecoveryCodesParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, arg CountUnusedRecoveryCodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedRecoveryCodes, arg.UserID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :one
INSERT INTO recovery_codes (id, user_id, project_id, code_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, project_id, code_hash, used, created_at, used_at
`

type CreateRecoveryCodeParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
	CodeHash  string `json:"code_hash"`
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) (RecoveryCode, error) {
	row := q.db.QueryRow(ctx, createRecoveryCode,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.CodeHash,
	)
	var i RecoveryCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.CodeHash,
		&i.Used,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteRecoveryCodesByUser = `-- name: DeleteRecoveryCodesByUser :exec
DELETE FROM recovery_codes WHERE user_id = $1 AND project_id = $2
`

type DeleteRecoveryCodesByUserParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteRecoveryCodesByUser(ctx context.Context, arg DeleteRecoveryCodesByUserParams) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodesByUser, arg.UserID, arg.ProjectID)
	return err
}

const listUnusedRecoveryCodes = `-- name: ListUnusedRecoveryCodes :many
SELECT id, user_id, project_id, code_hash, used, created_at, used_at FROM recovery_codes
WHERE user_id = $1 AND project_id = $2 AND used = false
ORDER BY created_at ASC
`

type ListUnusedRecoveryCodesParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) ListUnusedRecoveryCodes(ctx context.Context, arg ListUnusedRecoveryCodesParams) ([]RecoveryCode, error) {
	rows, err := q.db.Query(ctx, listUnusedRecoveryCodes, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryCode{}
	for rows.Next() {
		var i RecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.CodeHash,
			&i.Used,
			&i.CreatedAt,
			&i.UsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :exec
UPDATE recovery_codes SET used = true, used_at = now()
WHERE id = $1 AND project_id = $2
`

type MarkRecoveryCodeUsedParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, arg MarkRecoveryCodeUsedParams) error {
	_, err := q.db.Exec(ctx, markRecoveryCodeUsed, arg.ID, arg.ProjectID)
	return err
}
