// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSessionsByProject = `-- name: CountActiveSessionsByProject :one
SELECT count(*) FROM sessions WHERE project_id = $1 AND revoked_at IS NULL
`

func (q *Queries) CountActiveSessionsByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessionsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveSessionsByUser = `-- name: CountActiveSessionsByUser :one
SELECT count(*) FROM sessions WHERE user_id = $1 AND project_id = $2 AND revoked_at IS NULL
`

type CountActiveSessionsByUserParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) CountActiveSessionsByUser(ctx context.Context, arg CountActiveSessionsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessionsByUser, arg.UserID, arg.ProjectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, project_id, user_id, ip, user_agent, device_fp_hash, acr, amr, idle_timeout_at, abs_timeout_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, project_id, user_id, ip, user_agent, device_fp_hash, acr, amr, idle_timeout_at, abs_timeout_at, last_activity, revoked_at, created_at
`

type CreateSessionParams struct {
	ID            string             `json:"id"`
	ProjectID     string             `json:"project_id"`
	UserID        string             `json:"user_id"`
	Ip            *string            `json:"ip"`
	UserAgent     *string            `json:"user_agent"`
	DeviceFpHash  *string            `json:"device_fp_hash"`
	Acr           string             `json:"acr"`
	Amr           []byte             `json:"amr"`
	IdleTimeoutAt pgtype.Timestamptz `json:"idle_timeout_at"`
	AbsTimeoutAt  pgtype.Timestamptz `json:"abs_timeout_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.Ip,
		arg.UserAgent,
		arg.DeviceFpHash,
		arg.Acr,
		arg.Amr,
		arg.IdleTimeoutAt,
		arg.AbsTimeoutAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Ip,
		&i.UserAgent,
		&i.DeviceFpHash,
		&i.Acr,
		&i.Amr,
		&i.IdleTimeoutAt,
		&i.AbsTimeoutAt,
		&i.LastActivity,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, project_id, user_id, ip, user_agent, device_fp_hash, acr, amr, idle_timeout_at, abs_timeout_at, last_activity, revoked_at, created_at FROM sessions WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Ip,
		&i.UserAgent,
		&i.DeviceFpHash,
		&i.Acr,
		&i.Amr,
		&i.IdleTimeoutAt,
		&i.AbsTimeoutAt,
		&i.LastActivity,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByProject = `-- name: GetSessionByProject :one
SELECT id, project_id, user_id, ip, user_agent, device_fp_hash, acr, amr, idle_timeout_at, abs_timeout_at, last_activity, revoked_at, created_at FROM sessions WHERE id = $1 AND project_id = $2 AND revoked_at IS NULL
`

type GetSessionByProjectParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetSessionByProject(ctx context.Context, arg GetSessionByProjectParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByProject, arg.ID, arg.ProjectID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Ip,
		&i.UserAgent,
		&i.DeviceFpHash,
		&i.Acr,
		&i.Amr,
		&i.IdleTimeoutAt,
		&i.AbsTimeoutAt,
		&i.LastActivity,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByProjectAndUser = `-- name: GetSessionByProjectAndUser :one
SELECT id, project_id, user_id, ip, user_agent, device_fp_hash, acr, amr, idle_timeout_at, abs_timeout_at, last_activity, revoked_at, created_at FROM sessions WHERE id = $1 AND project_id = $2 AND user_id = $3 AND revoked_at IS NULL
`

type GetSessionByProjectAndUserParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
	UserID    string `json:"user_id"`
}

func (q *Queries) GetSessionByProjectAndUser(ctx context.Context, arg GetSessionByProjectAndUserParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByProjectAndUser, arg.ID, arg.ProjectID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.Ip,
		&i.UserAgent,
		&i.DeviceFpHash,
		&i.Acr,
		&i.Amr,
		&i.IdleTimeoutAt,
		&i.AbsTimeoutAt,
		&i.LastActivity,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, project_id, user_id, ip, user_agent, device_fp_hash, acr, amr, idle_timeout_at, abs_timeout_at, last_activity, revoked_at, created_at FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListActiveSessions(ctx context.Context, userID string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Ip,
			&i.UserAgent,
			&i.DeviceFpHash,
			&i.Acr,
			&i.Amr,
			&i.IdleTimeoutAt,
			&i.AbsTimeoutAt,
			&i.LastActivity,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSessionsByProject = `-- name: ListActiveSessionsByProject :many
SELECT id, project_id, user_id, ip, user_agent, device_fp_hash, acr, amr, idle_timeout_at, abs_timeout_at, last_activity, revoked_at, created_at FROM sessions
WHERE user_id = $1 AND project_id = $2 AND revoked_at IS NULL
ORDER BY created_at DESC
`

type ListActiveSessionsByProjectParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) ListActiveSessionsByProject(ctx context.Context, arg ListActiveSessionsByProjectParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByProject, arg.UserID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.UserID,
			&i.Ip,
			&i.UserAgent,
			&i.DeviceFpHash,
			&i.Acr,
			&i.Amr,
			&i.IdleTimeoutAt,
			&i.AbsTimeoutAt,
			&i.LastActivity,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionByProject = `-- name: RevokeSessionByProject :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1 AND project_id = $2 AND revoked_at IS NULL
`

type RevokeSessionByProjectParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) RevokeSessionByProject(ctx context.Context, arg RevokeSessionByProjectParams) error {
	_, err := q.db.Exec(ctx, revokeSessionByProject, arg.ID, arg.ProjectID)
	return err
}

const revokeUserSessions = `-- name: RevokeUserSessions :exec
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeUserSessions, userID)
	return err
}

const revokeUserSessionsByProject = `-- name: RevokeUserSessionsByProject :exec
UPDATE sessions SET revoked_at = now()
WHERE user_id = $1 AND project_id = $2 AND revoked_at IS NULL
`

type RevokeUserSessionsByProjectParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) RevokeUserSessionsByProject(ctx context.Context, arg RevokeUserSessionsByProjectParams) error {
	_, err := q.db.Exec(ctx, revokeUserSessionsByProject, arg.UserID, arg.ProjectID)
	return err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE sessions SET last_activity = now(), idle_timeout_at = $2
WHERE id = $1 AND revoked_at IS NULL
`

type UpdateSessionActivityParams struct {
	ID            string             `json:"id"`
	IdleTimeoutAt pgtype.Timestamptz `json:"idle_timeout_at"`
}

func (q *Queries) UpdateSessionActivity(ctx context.Context, arg UpdateSessionActivityParams) error {
	_, err := q.db.Exec(ctx, updateSessionActivity, arg.ID, arg.IdleTimeoutAt)
	return err
}
