// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
)

const banUser = `-- name: BanUser :exec
UPDATE users SET banned = true, ban_reason = $2, updated_at = now()
WHERE id = $1
`

type BanUserParams struct {
	ID        string  `json:"id"`
	BanReason *string `json:"ban_reason"`
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.Exec(ctx, banUser, arg.ID, arg.BanReason)
	return err
}

const countUsersByProject = `-- name: CountUsersByProject :one
SELECT count(*) FROM users WHERE project_id = $1
`

func (q *Queries) CountUsersByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, project_id, email_encrypted, email_hash, password_hash, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, email_encrypted, email_hash, password_hash, email_verified, banned, ban_reason, metadata, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID             string  `json:"id"`
	ProjectID      string  `json:"project_id"`
	EmailEncrypted []byte  `json:"email_encrypted"`
	EmailHash      []byte  `json:"email_hash"`
	PasswordHash   *string `json:"password_hash"`
	Metadata       []byte  `json:"metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.ProjectID,
		arg.EmailEncrypted,
		arg.EmailHash,
		arg.PasswordHash,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EmailEncrypted,
		&i.EmailHash,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Banned,
		&i.BanReason,
		&i.Metadata,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getInactiveUsers = `-- name: GetInactiveUsers :many
SELECT id, project_id FROM users
WHERE last_login_at < now() - make_interval(days => $1::int)
AND banned = false
`

type GetInactiveUsersRow struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetInactiveUsers(ctx context.Context, dollar_1 int32) ([]GetInactiveUsersRow, error) {
	rows, err := q.db.Query(ctx, getInactiveUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInactiveUsersRow{}
	for rows.Next() {
		var i GetInactiveUsersRow
		if err := rows.Scan(&i.ID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmailHash = `-- name: GetUserByEmailHash :one
SELECT id, project_id, email_encrypted, email_hash, password_hash, email_verified, banned, ban_reason, metadata, last_login_at, created_at, updated_at FROM users WHERE project_id = $1 AND email_hash = $2
`

type GetUserByEmailHashParams struct {
	ProjectID string `json:"project_id"`
	EmailHash []byte `json:"email_hash"`
}

func (q *Queries) GetUserByEmailHash(ctx context.Context, arg GetUserByEmailHashParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailHash, arg.ProjectID, arg.EmailHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EmailEncrypted,
		&i.EmailHash,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Banned,
		&i.BanReason,
		&i.Metadata,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, project_id, email_encrypted, email_hash, password_hash, email_verified, banned, ban_reason, metadata, last_login_at, created_at, updated_at FROM users WHERE id = $1 AND project_id = $2
`

type GetUserByIDParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.ProjectID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EmailEncrypted,
		&i.EmailHash,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Banned,
		&i.BanReason,
		&i.Metadata,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByProject = `-- name: ListUsersByProject :many
SELECT id, project_id, email_encrypted, email_hash, password_hash, email_verified, banned, ban_reason, metadata, last_login_at, created_at, updated_at FROM users WHERE project_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListUsersByProjectParams struct {
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListUsersByProject(ctx context.Context, arg ListUsersByProjectParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EmailEncrypted,
			&i.EmailHash,
			&i.PasswordHash,
			&i.EmailVerified,
			&i.Banned,
			&i.BanReason,
			&i.Metadata,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users SET banned = false, ban_reason = NULL, updated_at = now()
WHERE id = $1
`

func (q *Queries) UnbanUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, unbanUser, id)
	return err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :exec
UPDATE users SET email_verified = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerified, id)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = now(), updated_at = now()
WHERE id = $1 AND project_id = $2
`

type UpdateUserLastLoginParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, arg.ID, arg.ProjectID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now()
WHERE id = $1 AND project_id = $3
`

type UpdateUserPasswordParams struct {
	ID           string  `json:"id"`
	PasswordHash *string `json:"password_hash"`
	ProjectID    string  `json:"project_id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash, arg.ProjectID)
	return err
}
