// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const banUser = `-- name: BanUser :exec
UPDATE users SET banned = true, ban_reason = $2, updated_at = now()
WHERE id = $1 AND project_id = $3
`

type BanUserParams struct {
	ID        string  `json:"id"`
	BanReason *string `json:"ban_reason"`
	ProjectID string  `json:"project_id"`
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) error {
	_, err := q.db.Exec(ctx, banUser, arg.ID, arg.BanReason, arg.ProjectID)
	return err
}

const countActiveUsersByProject = `-- name: CountActiveUsersByProject :one
SELECT count(*) FROM users
WHERE project_id = $1
  AND last_login_at > now() - interval '30 days'
`

func (q *Queries) CountActiveUsersByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsersByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByProject = `-- name: CountUsersByProject :one
SELECT count(*) FROM users WHERE project_id = $1
`

func (q *Queries) CountUsersByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, project_id, email_encrypted, email_hash, password_hash, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, email_encrypted, email_hash, password_hash, email_verified, banned, ban_reason, metadata, last_login_at, created_at, updated_at, has_mfa
`

type CreateUserParams struct {
	ID             string  `json:"id"`
	ProjectID      string  `json:"project_id"`
	EmailEncrypted []byte  `json:"email_encrypted"`
	EmailHash      []byte  `json:"email_hash"`
	PasswordHash   *string `json:"password_hash"`
	Metadata       []byte  `json:"metadata"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.ProjectID,
		arg.EmailEncrypted,
		arg.EmailHash,
		arg.PasswordHash,
		arg.Metadata,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EmailEncrypted,
		&i.EmailHash,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Banned,
		&i.BanReason,
		&i.Metadata,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasMfa,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1 AND project_id = $2
`

type DeleteUserParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.Exec(ctx, deleteUser, arg.ID, arg.ProjectID)
	return err
}

const deleteUserConsents = `-- name: DeleteUserConsents :exec
DELETE FROM user_consents WHERE user_id = $1 AND project_id = $2
`

type DeleteUserConsentsParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteUserConsents(ctx context.Context, arg DeleteUserConsentsParams) error {
	_, err := q.db.Exec(ctx, deleteUserConsents, arg.UserID, arg.ProjectID)
	return err
}

const deleteUserEncryptionKeys = `-- name: DeleteUserEncryptionKeys :exec
DELETE FROM encryption_keys WHERE user_id = $1 AND project_id = $2
`

type DeleteUserEncryptionKeysParams struct {
	UserID    *string `json:"user_id"`
	ProjectID *string `json:"project_id"`
}

func (q *Queries) DeleteUserEncryptionKeys(ctx context.Context, arg DeleteUserEncryptionKeysParams) error {
	_, err := q.db.Exec(ctx, deleteUserEncryptionKeys, arg.UserID, arg.ProjectID)
	return err
}

const deleteUserPasswordHistory = `-- name: DeleteUserPasswordHistory :exec
DELETE FROM password_history WHERE user_id = $1
`

func (q *Queries) DeleteUserPasswordHistory(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserPasswordHistory, userID)
	return err
}

const deleteUserRefreshTokens = `-- name: DeleteUserRefreshTokens :exec
DELETE FROM refresh_tokens WHERE user_id = $1 AND project_id = $2
`

type DeleteUserRefreshTokensParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteUserRefreshTokens(ctx context.Context, arg DeleteUserRefreshTokensParams) error {
	_, err := q.db.Exec(ctx, deleteUserRefreshTokens, arg.UserID, arg.ProjectID)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1 AND project_id = $2
`

type DeleteUserSessionsParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteUserSessions(ctx context.Context, arg DeleteUserSessionsParams) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, arg.UserID, arg.ProjectID)
	return err
}

const deleteUserVerificationTokens = `-- name: DeleteUserVerificationTokens :exec
DELETE FROM verification_tokens WHERE user_id = $1 AND project_id = $2
`

type DeleteUserVerificationTokensParams struct {
	UserID    string `json:"user_id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) DeleteUserVerificationTokens(ctx context.Context, arg DeleteUserVerificationTokensParams) error {
	_, err := q.db.Exec(ctx, deleteUserVerificationTokens, arg.UserID, arg.ProjectID)
	return err
}

const getInactiveUsers = `-- name: GetInactiveUsers :many
SELECT id, project_id FROM users
WHERE (last_login_at < now() - make_interval(days => $1::int)
       OR (last_login_at IS NULL AND created_at < now() - make_interval(days => $1::int)))
AND banned = false
`

type GetInactiveUsersRow struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetInactiveUsers(ctx context.Context, dollar_1 int32) ([]GetInactiveUsersRow, error) {
	rows, err := q.db.Query(ctx, getInactiveUsers, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInactiveUsersRow{}
	for rows.Next() {
		var i GetInactiveUsersRow
		if err := rows.Scan(&i.ID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmailHash = `-- name: GetUserByEmailHash :one
SELECT id, project_id, email_encrypted, email_hash, password_hash, email_verified, banned, ban_reason, metadata, last_login_at, created_at, updated_at, has_mfa FROM users WHERE project_id = $1 AND email_hash = $2
`

type GetUserByEmailHashParams struct {
	ProjectID string `json:"project_id"`
	EmailHash []byte `json:"email_hash"`
}

func (q *Queries) GetUserByEmailHash(ctx context.Context, arg GetUserByEmailHashParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailHash, arg.ProjectID, arg.EmailHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EmailEncrypted,
		&i.EmailHash,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Banned,
		&i.BanReason,
		&i.Metadata,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasMfa,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, project_id, email_encrypted, email_hash, password_hash, email_verified, banned, ban_reason, metadata, last_login_at, created_at, updated_at, has_mfa FROM users WHERE id = $1 AND project_id = $2
`

type GetUserByIDParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.ProjectID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EmailEncrypted,
		&i.EmailHash,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Banned,
		&i.BanReason,
		&i.Metadata,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HasMfa,
	)
	return i, err
}

const listUsersByEmailHash = `-- name: ListUsersByEmailHash :many
SELECT id, project_id, email_encrypted, email_hash, password_hash, email_verified, banned, ban_reason, metadata, last_login_at, created_at, updated_at, has_mfa FROM users
WHERE project_id = $1 AND email_hash = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListUsersByEmailHashParams struct {
	ProjectID string `json:"project_id"`
	EmailHash []byte `json:"email_hash"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListUsersByEmailHash(ctx context.Context, arg ListUsersByEmailHashParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByEmailHash, arg.ProjectID, arg.EmailHash, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EmailEncrypted,
			&i.EmailHash,
			&i.PasswordHash,
			&i.EmailVerified,
			&i.Banned,
			&i.BanReason,
			&i.Metadata,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasMfa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByProject = `-- name: ListUsersByProject :many
SELECT id, project_id, email_encrypted, email_hash, password_hash, email_verified, banned, ban_reason, metadata, last_login_at, created_at, updated_at, has_mfa FROM users WHERE project_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListUsersByProjectParams struct {
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
	Offset    int32  `json:"offset"`
}

func (q *Queries) ListUsersByProject(ctx context.Context, arg ListUsersByProjectParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByProject, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EmailEncrypted,
			&i.EmailHash,
			&i.PasswordHash,
			&i.EmailVerified,
			&i.Banned,
			&i.BanReason,
			&i.Metadata,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasMfa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersCursor = `-- name: ListUsersCursor :many
SELECT id, project_id, email_encrypted, email_hash, password_hash, email_verified, banned, ban_reason, metadata, last_login_at, created_at, updated_at, has_mfa FROM users
WHERE project_id = $1
  AND (created_at < $2 OR (created_at = $2 AND id < $3))
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListUsersCursorParams struct {
	ProjectID       string             `json:"project_id"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        string             `json:"cursor_id"`
	Lim             int32              `json:"lim"`
}

func (q *Queries) ListUsersCursor(ctx context.Context, arg ListUsersCursorParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersCursor,
		arg.ProjectID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EmailEncrypted,
			&i.EmailHash,
			&i.PasswordHash,
			&i.EmailVerified,
			&i.Banned,
			&i.BanReason,
			&i.Metadata,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasMfa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersCursorBanned = `-- name: ListUsersCursorBanned :many
SELECT id, project_id, email_encrypted, email_hash, password_hash, email_verified, banned, ban_reason, metadata, last_login_at, created_at, updated_at, has_mfa FROM users
WHERE project_id = $1
  AND banned = $2
  AND (created_at < $3 OR (created_at = $3 AND id < $4))
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListUsersCursorBannedParams struct {
	ProjectID       string             `json:"project_id"`
	Banned          bool               `json:"banned"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursor_created_at"`
	CursorID        string             `json:"cursor_id"`
	Lim             int32              `json:"lim"`
}

func (q *Queries) ListUsersCursorBanned(ctx context.Context, arg ListUsersCursorBannedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersCursorBanned,
		arg.ProjectID,
		arg.Banned,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EmailEncrypted,
			&i.EmailHash,
			&i.PasswordHash,
			&i.EmailVerified,
			&i.Banned,
			&i.BanReason,
			&i.Metadata,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasMfa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersFirst = `-- name: ListUsersFirst :many
SELECT id, project_id, email_encrypted, email_hash, password_hash, email_verified, banned, ban_reason, metadata, last_login_at, created_at, updated_at, has_mfa FROM users
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type ListUsersFirstParams struct {
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListUsersFirst(ctx context.Context, arg ListUsersFirstParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersFirst, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EmailEncrypted,
			&i.EmailHash,
			&i.PasswordHash,
			&i.EmailVerified,
			&i.Banned,
			&i.BanReason,
			&i.Metadata,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasMfa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersFirstBanned = `-- name: ListUsersFirstBanned :many
SELECT id, project_id, email_encrypted, email_hash, password_hash, email_verified, banned, ban_reason, metadata, last_login_at, created_at, updated_at, has_mfa FROM users
WHERE project_id = $1 AND banned = $2
ORDER BY created_at DESC, id DESC
LIMIT $3
`

type ListUsersFirstBannedParams struct {
	ProjectID string `json:"project_id"`
	Banned    bool   `json:"banned"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListUsersFirstBanned(ctx context.Context, arg ListUsersFirstBannedParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersFirstBanned, arg.ProjectID, arg.Banned, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EmailEncrypted,
			&i.EmailHash,
			&i.PasswordHash,
			&i.EmailVerified,
			&i.Banned,
			&i.BanReason,
			&i.Metadata,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HasMfa,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unbanUser = `-- name: UnbanUser :exec
UPDATE users SET banned = false, ban_reason = NULL, updated_at = now()
WHERE id = $1 AND project_id = $2
`

type UnbanUserParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) UnbanUser(ctx context.Context, arg UnbanUserParams) error {
	_, err := q.db.Exec(ctx, unbanUser, arg.ID, arg.ProjectID)
	return err
}

const updateUserEmailAndMetadata = `-- name: UpdateUserEmailAndMetadata :exec
UPDATE users SET
  email_verified = $2,
  metadata = $3,
  updated_at = now()
WHERE id = $1 AND project_id = $4
`

type UpdateUserEmailAndMetadataParams struct {
	ID            string `json:"id"`
	EmailVerified bool   `json:"email_verified"`
	Metadata      []byte `json:"metadata"`
	ProjectID     string `json:"project_id"`
}

func (q *Queries) UpdateUserEmailAndMetadata(ctx context.Context, arg UpdateUserEmailAndMetadataParams) error {
	_, err := q.db.Exec(ctx, updateUserEmailAndMetadata,
		arg.ID,
		arg.EmailVerified,
		arg.Metadata,
		arg.ProjectID,
	)
	return err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :exec
UPDATE users SET email_verified = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerified, id)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users SET last_login_at = now(), updated_at = now()
WHERE id = $1 AND project_id = $2
`

type UpdateUserLastLoginParams struct {
	ID        string `json:"id"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) UpdateUserLastLogin(ctx context.Context, arg UpdateUserLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, arg.ID, arg.ProjectID)
	return err
}

const updateUserMetadata = `-- name: UpdateUserMetadata :exec
UPDATE users SET metadata = $2, updated_at = now()
WHERE id = $1 AND project_id = $3
`

type UpdateUserMetadataParams struct {
	ID        string `json:"id"`
	Metadata  []byte `json:"metadata"`
	ProjectID string `json:"project_id"`
}

func (q *Queries) UpdateUserMetadata(ctx context.Context, arg UpdateUserMetadataParams) error {
	_, err := q.db.Exec(ctx, updateUserMetadata, arg.ID, arg.Metadata, arg.ProjectID)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2, updated_at = now()
WHERE id = $1 AND project_id = $3
`

type UpdateUserPasswordParams struct {
	ID           string  `json:"id"`
	PasswordHash *string `json:"password_hash"`
	ProjectID    string  `json:"project_id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash, arg.ProjectID)
	return err
}
