// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_consents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConsent = `-- name: CreateConsent :one
INSERT INTO user_consents (id, user_id, project_id, purpose, granted, version, ip, user_agent, granted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, project_id, purpose, granted, version, ip, user_agent, granted_at, revoked_at, created_at
`

type CreateConsentParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	ProjectID string             `json:"project_id"`
	Purpose   string             `json:"purpose"`
	Granted   bool               `json:"granted"`
	Version   *string            `json:"version"`
	Ip        *string            `json:"ip"`
	UserAgent *string            `json:"user_agent"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
}

func (q *Queries) CreateConsent(ctx context.Context, arg CreateConsentParams) (UserConsent, error) {
	row := q.db.QueryRow(ctx, createConsent,
		arg.ID,
		arg.UserID,
		arg.ProjectID,
		arg.Purpose,
		arg.Granted,
		arg.Version,
		arg.Ip,
		arg.UserAgent,
		arg.GrantedAt,
	)
	var i UserConsent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProjectID,
		&i.Purpose,
		&i.Granted,
		&i.Version,
		&i.Ip,
		&i.UserAgent,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUserConsents = `-- name: GetUserConsents :many
SELECT id, user_id, project_id, purpose, granted, version, ip, user_agent, granted_at, revoked_at, created_at FROM user_consents WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetUserConsents(ctx context.Context, userID string) ([]UserConsent, error) {
	rows, err := q.db.Query(ctx, getUserConsents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserConsent{}
	for rows.Next() {
		var i UserConsent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProjectID,
			&i.Purpose,
			&i.Granted,
			&i.Version,
			&i.Ip,
			&i.UserAgent,
			&i.GrantedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeConsent = `-- name: RevokeConsent :exec
UPDATE user_consents SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeConsent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeConsent, id)
	return err
}
