// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_tokens.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerificationToken = `-- name: CreateVerificationToken :one
INSERT INTO verification_tokens (id, project_id, user_id, token_hash, type, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, user_id, token_hash, type, used, created_at, expires_at
`

type CreateVerificationTokenParams struct {
	ID        string             `json:"id"`
	ProjectID string             `json:"project_id"`
	UserID    string             `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	Type      string             `json:"type"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, createVerificationToken,
		arg.ID,
		arg.ProjectID,
		arg.UserID,
		arg.TokenHash,
		arg.Type,
		arg.ExpiresAt,
	)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.Used,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getVerificationTokenByHash = `-- name: GetVerificationTokenByHash :one
SELECT id, project_id, user_id, token_hash, type, used, created_at, expires_at FROM verification_tokens WHERE token_hash = $1 AND used = false
`

func (q *Queries) GetVerificationTokenByHash(ctx context.Context, tokenHash []byte) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, getVerificationTokenByHash, tokenHash)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.UserID,
		&i.TokenHash,
		&i.Type,
		&i.Used,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markVerificationTokenUsed = `-- name: MarkVerificationTokenUsed :exec
UPDATE verification_tokens SET used = true WHERE id = $1
`

func (q *Queries) MarkVerificationTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markVerificationTokenUsed, id)
	return err
}
